
const dummyData = [
  
    { id: 1,
      name: "Little Italy",
      image:"https://static.uengage.in/uploads/5/image-7626-1671430524.jpg",
      discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
      price:299,
      rating:4, 
    },

    { id: 2,
        name: "The Art of Pizza",
        image:"https://static.uengage.in/uploads/5/image-7635-1671430602.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:399,
        rating:4, 
      },

      { id: 3,
        name: "Olive Garden",
        image:"https://static.uengage.in/uploads/5/image-5275-1671430619.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:499,
        rating:3, 
      },

      { id: 4,
        name: "Union Pizzeria",
        image:"https://static.uengage.in/uploads/5/image-5241-1671268932.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:199,
        rating:5, 
      },

      { id: 5,
        name: "My Cheese",
        image:"https://static.uengage.in/uploads/5/image-3428-1671268931.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:299,
        rating:3, 
      },

      { id: 6,
        name: "Paradise",
        image:"https://static.uengage.in/uploads/5/image-8766-1671430627.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:399,
        rating:5, 
      },

      { id: 7,
        name: "Prima Pizza",
        image:"https://static.uengage.in/uploads/5/image-5241-1671268932.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:499,
        rating:5, 
      },

      { id: 8,
        name: "melted cheese",
        image:"https://static.uengage.in/uploads/5/image-6528-1671430521.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:299,
        rating:3, 
      },

      { id: 9,
        name: "Heavenly Delights",
        image:"https://static.uengage.in/uploads/5/image-4226-1671430553.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:399,
        rating:3, 
      },
      { id: 10,
        name: "Speedy Gonzalez",
        image:"https://static.uengage.in/uploads/5/image-2562-1671430581.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:499,
        rating:2, 
      },
      { id: 11,
        name: "Hot Stone Pizzeria",
        image:"https://static.uengage.in/uploads/5/image-7635-1671430602.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:299,
        rating:5, 
      },
      { id: 12,
        name: "Buttet Crust",
        image:"https://static.uengage.in/uploads/5/image-2132-1671430612.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:199,
        rating:4, 
      },
      { id: 13,
        name: "Dish Pizzeria",
        image:"https://static.uengage.in/uploads/5/image-1344-1671430665.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:199,
        rating:3, 
      },
      { id: 14,
        name: "Slice of Sicily",
        image:"https://static.uengage.in/uploads/5/image-8766-1671430627.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:599,
        rating:5, 
      },
      { id: 15,
        name: "Punch Pizza",
        image:"https://static.uengage.in/uploads/5/image-4352-1671110991.jpg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:299,
        rating:3, 
      },
      { id: 16,
        name: "Spark and Pizza",
        image:"https://static.uengage.in/uploads/5/image-5994-1671430683.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:499,
        rating:4, 
      },
      { id: 17,
        name: "Sausage Fest",
        image:"https://static.uengage.in/uploads/5/image-5994-1671430683.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:399,
        rating:4, 
      },
      { id: 18,
        name: "Fajita Factor",
        image:"https://static.uengage.in/uploads/5/image-1343-1671430630.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:299,
        rating:3, 
      },
      { id: 19,
        name: "Pizza Divine",
        image:"https://static.uengage.in/uploads/5/image-4144-1671430694.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:199,
        rating:5, 
      },
      { id: 20,
        name: "Red Peddler",
        image:"https://static.uengage.in/uploads/5/image-8173-1671430696.jpeg",
        discriptions:"Among the great classics of “fake pizza” is pizza made with cauliflower. Ideal for those on a diet or perhaps who are gluten intolerant and don’t want to give up the taste of pizza.",
        price:499,
        rating:3, 
      },
]

export default dummyData